FROM python:3.12-slim

RUN apt-get update && \
    apt upgrade -y && \
    pip3 install --upgrade pip && \
    mkdir /src

RUN apt -y install graphviz
RUN apt-get update
RUN apt -y install libcairo2-dev libjpeg-dev libgif-dev libopenblas-dev build-essential libopenblas-dev

RUN pip install torch
COPY ./requirements-modern.txt /requirements.txt
RUN pip install --requirement /requirements.txt

WORKDIR /code
