FROM python:3.10-slim

RUN apt-get update && \
    apt upgrade -y && \
    pip3 install --upgrade pip && \
    mkdir /src

RUN apt -y install graphviz
RUN apt-get update
RUN apt -y install build-essential libcairo2-dev pkg-config libhdf5-dev
# libcairo2-dev libjpeg-dev libgif-dev libopenblas-dev build-essential libopenblas-dev

RUN pip install torch h5py
COPY ./requirements-industrial.txt /requirements.txt
RUN pip install --requirement /requirements.txt

WORKDIR /code
