FROM python:3.10-slim

RUN apt-get update && \
    apt upgrade -y && \
    pip3 install --upgrade pip && \
    mkdir /src

RUN apt -y install graphviz
RUN apt-get update
RUN apt -y install build-essential


COPY ./requirements.txt /requirements.txt

RUN pip install torch
RUN pip install --requirement /requirements.txt

WORKDIR /code
