name: Test

on:
  push:
    paths-ignore:
      - "docs/**"
      - "images/**"
      - "*.md"
      - "IndustrialStatistics/**"

  pull_request:
    paths-ignore:
      - "docs/**"
      - "images/**"
      - "*.md"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-modern:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # 3.11-dev fails due to compilation of scipy
      # 
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # - name: Windows specific setup
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     set BLAS=C:/Program Files/R/R-4.3.3/bin/x64Rblas.dll
      #     set BLAS=C:/Program Files/R/R-4.3.3/bin
      # - name: Install graphviz
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     sudo apt install -y graphviz
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install dependencies
        run: |
          conda install scipy.
          pip install --upgrade pip
          pip install --upgrade wheel
          # pip install scipy
          pip install -r requirements-modern.txt
          cat requirements-modern.txt

      - name: Execute notebooks
        env:
          PYDEVD_DISABLE_FILE_VALIDATION: 1 
        run: |
          jupyter nbconvert --to notebook --execute ModernStatistics/notebooks/Chap001.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/notebooks/Chap002.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/notebooks/Chap003.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/notebooks/Chap004.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/notebooks/Chap005.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/notebooks/Chap006.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/notebooks/Chap007.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/notebooks/Chap008.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/solutions/Solution_Chap001_ex.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/solutions/Solution_Chap002_ex.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/solutions/Solution_Chap003_ex.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/solutions/Solution_Chap004_ex.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/solutions/Solution_Chap005_ex.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/solutions/Solution_Chap006_ex.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/solutions/Solution_Chap007_ex.ipynb
          jupyter nbconvert --to notebook --execute ModernStatistics/solutions/Solution_Chap008_ex.ipynb

  build-industrial:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Linux packages
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y graphviz
          sudo apt-get install libblas-dev liblapack-dev

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade wheel
          pip install scipy
          pip install -r requirements-industrial.txt
          pip freeze

      - name: Execute notebooks
        env:
          PYDEVD_DISABLE_FILE_VALIDATION: 1 
        run: |
          jupyter nbconvert --to notebook --execute IndustrialStatistics/notebooks/Chap001.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/notebooks/Chap002.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/notebooks/Chap003.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/notebooks/Chap004.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/notebooks/Chap005.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/notebooks/Chap006.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/notebooks/Chap007.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/notebooks/Chap008.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/notebooks/Chap009.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/notebooks/Chap010.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/notebooks/Chap011.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/solutions/Solution_Chap001_ex.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/solutions/Solution_Chap002_ex.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/solutions/Solution_Chap003_ex.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/solutions/Solution_Chap004_ex.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/solutions/Solution_Chap005_ex.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/solutions/Solution_Chap006_ex.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/solutions/Solution_Chap007_ex.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/solutions/Solution_Chap008_ex.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/solutions/Solution_Chap009_ex.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/solutions/Solution_Chap010_ex.ipynb
          jupyter nbconvert --to notebook --execute IndustrialStatistics/solutions/Solution_Chap011_ex.ipynb
